name: LightUtils
version: '${version}'
main: ink.neokoni.lightutils.LightUtils
folia-supported: true
api-version: '1.21.4'

authors: ["Neokoni"]
website: https://github.com/Craft233/LightUtils

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true