name: LightUtils
version: '${version}'
main: ink.neokoni.lightutils.LightUtils
folia-supported: true
api-version: '1.21.4'

authors: ["Neokoni"]
website: https://github.com/Craft233/LightUtils

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: false
      join-classpath: true
    ProtocolSupport:
      load: BEFORE
      required: false
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true
    ViaBackwards:
      load: BEFORE
      required: false
      join-classpath: true
    ViaRewind:
      load: BEFORE
      required: false
      join-classpath: true
    Geyser-Spigot:
      load: BEFORE
      required: false
      join-classpath: true