name: LightUtils
version: '${version}'
main: ink.neokoni.lightutils.lightutils.LightUtils
folia-supported: true
api-version: '1.21'

authors: ["Neokoni"]
website: https://github.com/Craft233/LightUtils

dependencies:
  PlaceholderAPI:
    load: BEFORE
    required: true
    join-classpath: true